### PR TITLE
chore: add openshift pipelines hack script override

### PR DESCRIPTION
**Pull request by jrangelramos**
- Adding overrides as an alternative to git patch for midstream sync
- Adding openshift pipelines install script

### CODE REVIEW

**Review by lance — COMMENTED** [review]
Nice, Jefferson. I am curious who runs this override script and how?

**Comment by jrangelramos** [comment]
The idea of having overrides, is inspired on what @cardil suggested few days ago with his [deviate](https://github.com/cardil/deviate). There are cases (like a full override, or new files) that just having the whole plan file is easier to maintain compared to git patches, so we could have both an adopt patch or full replace when more appropriated.

**Comment by matejvasek** [comment]
@jrangelramos 
I tried to run the scrip:
```
Installing Openshift Pipelines...
Channel: pipelines-1.8 Target Version: "openshift-pipelines-operator-rh.v1.8.0"
subscription.operators.coreos.com/openshift-pipelines-operator-rh unchanged
error: unrecognized condition: "jsonpath={.status.state}=AtLatestKnown"
```
Any idea what's wrong?

**Comment by jrangelramos** [comment]
Did you have openshift pipelines previously installed (manually), or you're trying in a fresh cluster?

**Comment by jrangelramos** [comment]
oc client version possibly.. guess it needs to be 4.10+

**Pull request merged**
