### PR TITLE
[serverless-1.29.0] patch func deploy task

### PR DESCRIPTION
**Pull request by jrangelramos**
patch for func-deploy task to use midstream specific client

### CODE REVIEW

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by lance** [comment]
@jrangelramos what's the status on this?

**Comment by jrangelramos** [comment]
Hi Lance, can you pls bypass checks (failed tests)? Image will be available when it goes live.
We need this merged when docs get live

**Comment by lance** [comment]
/override "Func E2E OnCluster RT Test / On Cluster RT Test"
/override "Func E2E OnCluster Test / On Cluster Test"

**Pull request merged**
