### PR TITLE
[serverless-1.29.0] patch func deploy task for serverless 1.29.1

### PR DESCRIPTION
**Pull request by jrangelramos**
patch for func-deploy task to use midstream specific client built for 1.29.1

### CODE REVIEW

**Comment by jrangelramos** [comment]
hello @matejvasek @dsimansk , can we override failed tests on this one and get this merged?

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.x, ubuntu-latest)"
/override "On Cluster Test"

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.x, ubuntu-latest)"
/override "On Cluster Test (1.20.x, ubuntu-latest)"

**Comment by matejvasek** [comment]
Test here are failing because of Go version.

**Comment by matejvasek** [comment]
On 1.20.5 more test would pass.

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.5, ubuntu-latest)"
/override "On Cluster Test (1.20.5, ubuntu-latest)"

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.2, ubuntu-latest)"
/override "On Cluster Test (1.20.2, ubuntu-latest)"

**Pull request merged**
