### PR TITLE
[serverless-1.31] patch func deploy task for serverless 1.31.1

### PR DESCRIPTION
**Pull request by serverless-qe**
patch for func-deploy task to use midstream specific client built for 1.31.1

### CODE REVIEW

**Comment by matejvasek** [comment]
/override "Func E2E OnCluster Test / On Cluster Test (1.20.2, ubuntu-latest)"
/override "Func Integration Test / Integration Test (1.20.2, ubuntu-latest)"
/override "Func Unit Test / Unit Test (1.20.2, 17, ubuntu-latest)"

**Comment by jrangelramos** [comment]
new PR sent for this one https://github.com/openshift-knative/kn-plugin-func/pull/743

**Pull request closed without merging**
