### PR TITLE
[serverless-1.30] fix: bad connection handling for in cluster dialer

### PR DESCRIPTION
**Pull request by matejvasek**
backport https://github.com/knative/func/pull/1800
This makes `io: read/write on closed pipe` go away.

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @jrangelramos

**Comment by matejvasek** [comment]
@dsimansk please check this is a compatible change

**Comment by dsimansk** [comment]
/override "On Cluster RT Test (1.20.5, ubuntu-latest)"
/override "On Cluster Test (1.20.5, ubuntu-latest)"

**Pull request merged**
