### PR TITLE
[serverless-1.30] Update tekton dependency

### PR DESCRIPTION
**Pull request by matejvasek**
backport https://github.com/knative/func/pull/1753
This makes on cluster build work with tekton operator `1.10` and `1.11`.

### CODE REVIEW

**Comment by matejvasek** [comment]
PTAL @jrangelramos

**Comment by matejvasek** [comment]
@dsimansk please check this is a compatible change

**Comment by dsimansk** [comment]
@matejvasek @jrangelramos any chance to get the GH actions fixed? Or is it ok to override them for now?

**Pull request merged**
