### PR TITLE
[serverless-1.28.0] patch func-deploy task to midstream specific impletementation

### PR DESCRIPTION
**Pull request by jrangelramos**
Patching func-deploy task to use midstream specific kn client image.

### CODE REVIEW

**Comment by lance** [comment]
e2e tests are failing with the following error.

```
        2023/03/20 16:52:28 Error executing command: fork/exec /ko-app/kn: no such file or directory
```

**Comment by jrangelramos** [comment]
This is to support SRVOCF-518

**Comment by matejvasek** [comment]
/override "Func E2E OnCluster RT Test / On Cluster RT Test (1.18.x, ubuntu-latest)"
/override "Func E2E OnCluster Test / On Cluster Test (1.18.x, ubuntu-latest)"

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.18.x, ubuntu-latest)"
/override "On Cluster Test (1.18.x, ubuntu-latest)"

**Pull request merged**
