### PR TITLE
[serverless-1.29.0] patch s2i task images

### PR DESCRIPTION
**Pull request by jrangelramos**
Patch s2i task to use supported images referenced on serverless operator

### CODE REVIEW

**Comment by jrangelramos** [comment]
/unhold
/cc @mgencur @lance 

GA images shall be available by end of July. For now we should use the same images as of the operator

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.2, ubuntu-latest)"
/override "On Cluster Test (1.20.2, ubuntu-latest)"

**Comment by matejvasek** [comment]
/override "On Cluster RT Test (1.20.x, ubuntu-latest)"
/override "On Cluster Test (1.20.x, ubuntu-latest)"

**Pull request merged**
